services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    # NAMA CONTAINER UNIK KELOMPOK 6
    container_name: jenkins-kel-6
    ports:
      # PORT UNIK KELOMPOK 6 (Agar tidak bentrok dengan kelompok lain)
      - "8086:8080"
      - "50006:50000"
    volumes:
      - jenkins_home_kel6:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./casc.yaml:/var/jenkins_home/casc.yaml:ro
    restart: unless-stopped

volumes:
  # VOLUME UNIK AGAR DATA TIDAK TERCAMPUR
  jenkins_home_kel6:
