pipeline {
    agent any
    
    environment {
        PROJECT_DIR = 'pertemuan-09-cicd/pbl-taskflow-go'
        // DATABASE_URL disiapkan untuk S2 Integration Test nanti
        DATABASE_URL = "postgres://taskflow:taskflow_secret@db:5432/taskflow?sslmode=disable"
        // PINDAHKAN CACHE KE WORKSPACE AGAR TIDAK PERMISSION DENIED
        GOCACHE = "${WORKSPACE}/.cache"
    }

    stages {
        stage('Preparation') {
            agent {
                docker { 
                    image 'golang:1.22'
                    // Jalankan sebagai root agar tidak kena permission denied saat membuat cache
                    args '-u root'
                }
            }
            steps {
                dir("${env.PROJECT_DIR}") {
                    sh 'go mod download'
                }
            }
        }

        stage('Static Analysis') {
            agent {
                docker { 
                    image 'golang:1.22'
                    args '-u root'
                }
            }
            steps {
                dir("${env.PROJECT_DIR}") {
                    echo 'Running go vet...'
                    sh 'go vet ./...'
                }
            }
        }

        stage('Unit Testing & Race Detector') {
            agent {
                docker { 
                    image 'golang:1.22'
                    args '-u root'
                }
            }
            steps {
                dir("${env.PROJECT_DIR}") {
                    echo 'Running tests with race detector (CGO Enabled)...'
                    sh 'CGO_ENABLED=1 go test -v -race ./internal/service/... ./internal/validator/... ./internal/handler/...'
                }
            }
        }

        stage('Coverage Gate') {
            agent {
                docker { 
                    image 'golang:1.22'
                    args '-u root'
                }
            }
            steps {
                dir("${env.PROJECT_DIR}") {
                    script {
                        sh 'go test ./... -coverprofile=cov.out'
                        def coverage = sh(script: "go tool cover -func=cov.out | grep total | awk '{print \$3}' | sed 's/%//'", returnStdout: true).trim()
                        echo "Total project coverage: ${coverage}%"
                        
                        if (coverage.toFloat() < 75.0) {
                            error "❌ Pipeline Failed: Coverage (${coverage}%) is below 75%!"
                        } else {
                            echo "✅ Coverage Gate Passed!"
                        }
                    }
                }
            }
        }

        stage('Build Binary') {
            agent {
                docker { 
                    image 'golang:1.22'
                    args '-u root'
                }
            }
            steps {
                dir("${env.PROJECT_DIR}") {
                    echo 'Compiling application...'
                    sh 'go build -o bin/taskflow-api ./cmd/server'
                }
            }
        }
    }

    post {
        always {
            dir("${env.PROJECT_DIR}") {
                archiveArtifacts artifacts: 'cov.out', allowEmptyArchive: true
            }
        }
    }
}
